-- intialisation pour creer les tables dans le schema désiré: en premiere position dans le cas present
SET search_path TO ejb3inaction,public;

CREATE TABLE BILLING_DETAILS (
		BILLING_ID BIGINT NOT NULL,
		ACCOUNT_NUMBER VARCHAR(255),
		EXPIRY_DATE VARCHAR(255),
		ACCOUNT_TYPE VARCHAR(255)
	);
CREATE TABLE USERS (
		USER_ID VARCHAR(255) NOT NULL,
		FIRST_NAME VARCHAR(255) NOT NULL,
		LAST_NAME VARCHAR(255) NOT NULL,
		BIRTH_DATE DATE,
		USER_BILLING_ID BIGINT,
    	USER_TYPE VARCHAR(1)
	);
CREATE TABLE CATEGORIES (
		CATEGORY_ID BIGINT NOT NULL,
		CATEGORY_NAME VARCHAR(255),
		CREATE_DATE TIMESTAMP,
		CREATED_BY VARCHAR(255),
		PARENT_ID BIGINT
	);
CREATE TABLE ITEMS (
		ITEM_ID BIGINT NOT NULL,
		ITEM_NAME VARCHAR(255),
		BID_END_DATE TIMESTAMP,
		BID_START_DATE TIMESTAMP,
		CREATED_DATE TIMESTAMP,
		INITIAL_PRICE NUMERIC(10,2),
		SELLER_ID VARCHAR(255)
	);
CREATE TABLE CATEGORIES_ITEMS (
		CATEGORY_ID BIGINT NOT NULL,
		ITEM_ID BIGINT NOT NULL
	);